-- ============================================================
-- フラッシュ暗算 Web/PWA v3
-- Supabase Anonymous Auth 対応ランキング
-- ============================================================
--
-- 前提:
-- Supabase Dashboard
-- Authentication > Anonymous Sign-Ins = ON
--
-- nickname は表示名だけなので重複OKです。
-- player_id には Supabase Auth の auth.uid() を保存します。
-- run_id は1プレイごとのUUIDです。
--
-- Secret key / service_role key はブラウザに置かないでください。
-- ============================================================


-- ------------------------------------------------------------
-- 1. ランキング履歴テーブル
-- ------------------------------------------------------------

create table if not exists public.flash_scores (
  id bigint generated by default as identity primary key,

  -- Supabase Anonymous Auth user id
  player_id uuid not null default auth.uid(),

  -- 1プレイに1つ。二重送信対策。
  run_id uuid not null unique,

  nickname text not null,
  level integer not null,
  edition text not null default 'yellow',

  duration_ms bigint not null default 0,
  questions_answered integer not null default 0,
  client_version text not null default 'unknown',

  created_at timestamptz not null default now(),

  constraint flash_scores_nickname_length
    check (char_length(btrim(nickname)) between 1 and 12),

  constraint flash_scores_nickname_trimmed
    check (nickname = btrim(nickname)),

  constraint flash_scores_no_control_chars
    check (nickname !~ '[[:cntrl:]]'),

  constraint flash_scores_level_range
    check (level between 1 and 50),

  constraint flash_scores_duration_range
    check (duration_ms between 0 and 86400000),

  constraint flash_scores_questions_range
    check (questions_answered between 0 and 10000),

  constraint flash_scores_edition
    check (edition = 'yellow')
);


-- 既にv2テーブルを作っていた場合にもdefaultを更新。
alter table public.flash_scores
  alter column player_id set default auth.uid();


-- ------------------------------------------------------------
-- 2. RLS
-- ------------------------------------------------------------

alter table public.flash_scores enable row level security;

-- 未認証の anon ロールからは直接書き込ませない。
revoke all on table public.flash_scores from anon, authenticated;

-- Anonymous Authでログインしたユーザーは
-- PostgreSQL上では authenticated ロールになる。
grant insert on table public.flash_scores to authenticated;


drop policy if exists "public can submit flash scores"
  on public.flash_scores;

drop policy if exists "authenticated user can submit own flash score"
  on public.flash_scores;


create policy "authenticated user can submit own flash score"
on public.flash_scores
for insert
to authenticated
with check (
  (select auth.uid()) is not null

  -- 他人のuser idをplayer_idに入れることを禁止。
  and player_id = (select auth.uid())

  and char_length(btrim(nickname)) between 1 and 12
  and nickname = btrim(nickname)
  and nickname !~ '[[:cntrl:]]'

  and level between 1 and 50
  and duration_ms between 0 and 86400000
  and questions_answered between 0 and 10000
  and edition = 'yellow'
);


-- ------------------------------------------------------------
-- 3. Index
-- ------------------------------------------------------------

create index if not exists flash_scores_player_best_idx
on public.flash_scores (
  edition,
  player_id,
  level desc,
  created_at asc
);

create index if not exists flash_scores_rank_idx
on public.flash_scores (
  edition,
  level desc,
  created_at asc
);


-- ------------------------------------------------------------
-- 4. 公開ランキングRPC
--
-- player_id / run_id は返さない。
-- 同じauth.uid()のユーザーはベスト記録1件だけ。
-- 別ユーザーなら同じnicknameでも何人でも掲載される。
-- ------------------------------------------------------------

create or replace function public.get_flash_ranking(
  p_limit integer default 1000
)
returns table (
  nickname text,
  level integer,
  created_at timestamptz
)
language sql
security definer
set search_path = ''
stable
as $$
  select
    best.nickname,
    best.level,
    best.created_at
  from (
    select distinct on (s.player_id)
      s.player_id,
      s.nickname,
      s.level,
      s.created_at
    from public.flash_scores as s
    where s.edition = 'yellow'
    order by
      s.player_id,
      s.level desc,
      s.created_at asc
  ) as best
  order by
    best.level desc,
    best.created_at asc
  limit least(
    greatest(coalesce(p_limit, 1000), 1),
    1000
  );
$$;


-- 生テーブルのSELECT権限は与えない。
-- ランキングはこのRPC経由だけ。
revoke all on function public.get_flash_ranking(integer) from public;
revoke all on function public.get_flash_ranking(integer) from anon;
revoke all on function public.get_flash_ranking(integer) from authenticated;

grant execute on function public.get_flash_ranking(integer)
to authenticated;


-- ============================================================
-- 確認用
-- ============================================================
--
-- 実行後:
-- Database > Tables > flash_scores
--   RLS = Enabled
--
-- Policies:
--   authenticated user can submit own flash score
--
-- Authentication > Users:
--   Web版を初めて開くと匿名ユーザーが1人作成されます。
--
-- 同じブラウザではSupabase JSがsessionをlocalStorageに保持するため、
-- 通常は次回アクセスも同じ匿名ユーザーです。
--
-- ブラウザデータ削除・サインアウト・別端末では新しい匿名ユーザーになります。
-- バックアップJSONには認証トークンを保存しません。
-- ============================================================
